### ISSUE TITLE
Why the second tick-all after a call to after should succeed?

### ISSUE THREAD

**Issue by Yehouda** [Shinmera/promise#1]
https://github.com/Shinmera/promise/blob/81567b0677366cd93840c27f03f6c8e1e89f0e4a/test.lisp#L137

The check above fails for me, because **tick-all** returns nil. 

As as far as I can tell, that is because the previous call **tick-all** deregister all the promises. On enetring the previous call to **tick-all**, there are two promises (_main-promise_ and _after-promise_). **tick-all** ticks _main-promise,_ which is already successful, This causes a call to **succeed** on  _after-promise_ (inside the **handler** flet of **after**), and then deregisters _main-promise_. Then **tick-all** ticks _after-promise_, and since this is by now successful, it is also deregistered.

**Comment by Shinmera** [comment]
I'm not sure, it looks like a faulty test to me. Might have been a bug that I fixed since writing the tests.
